library(reticulate)
library(dplyr)
library(shiny)
library(shinyjs)
library(shinyBS)
library(shinycssloaders)
library(shinyWidgets)
library(shinydashboard)
library(shinyFiles)
library(spsComps)
library(colourpicker)
library(tools)
library(zip)
library(stringr)
library(BH)
library(DT)

# load encode hic data
encodehic <- read.table("https://s3.amazonaws.com/igv.org.app/encode/hic/hic.txt", header=T, sep="\t")
